version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: go.mongodb.org/mongo-driver
    versions:
    - 1.4.5
    - 1.4.6
    - 1.5.0
  - dependency-name: github.com/gdamore/tcell/v2
    versions:
    - 2.2.0
